global using System.Collections.Immutable;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using UnoMultiPlatformApp.DataContracts;
global using UnoMultiPlatformApp.DataContracts.Serialization;
global using UnoMultiPlatformApp.Models;
global using UnoMultiPlatformApp.Presentation;
global using UnoMultiPlatformApp.Services.Caching;
global using UnoMultiPlatformApp.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
